version: '3.8'

services:
  # PostgreSQL Database for Development
  postgres:
    image: postgres:15-alpine
    container_name: vulnerability_platform_db_dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: vulnerability_platform_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5433:5432"  # Different port to avoid conflicts
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - vulnerability_network_dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Prisma Studio for Development
  prisma-studio:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: vulnerability_platform_studio_dev
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://postgres:postgres123@postgres:5432/vulnerability_platform_dev
    ports:
      - "5555:5555"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - vulnerability_network_dev
    command: >
      sh -c "
        npm run prisma:generate &&
        npm run prisma:studio
      "

volumes:
  postgres_dev_data:
    driver: local

networks:
  vulnerability_network_dev:
    driver: bridge
